export const TOPICS = Object.freeze({
  SERVER_CHANNEL: "SERVER_MESSAGE",
  GAME_CHANNEL: "GAME_CHANNEL",
  CLIENT_CHANNEL: "CLIENT_CHANNEL",
  ROOM_CHANNEL: "ROOM_CHANNEL",
  ERROR_CHANNEL: "ERROR_CHANNEL",
});

export const TYPES = Object.freeze({
  GAME: {
    LEADERBOARD: "LEADERBOARD",
    SEND_DATA: "SEND_DATA",
    START: "START",
    OVER: "OVER",
  },
  CLIENT: {
    SELF_CONNECTED: "SELF_CONNECTED",
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    JOIN_ROOM: "JOINED_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
  },
  ROOM: {
    CREATE_ROOM: "CREATE_ROOM",
    REMOVE_ROOM: "REMOVE_ROOM",
    GET_ALL_ROOMS: "GET_ALL_ROOMS",
    GET_ALL_CLIENTS: "GET_ALL_CLIENTS",
    REMOVE_CLIENT_FROM_LIST: "REMOVE_CLIENT",
    ADD_CLIENT_TO_LIST: "ADD_CLIENT",
  },
});
