export const TOPICS = Object.freeze({
  SERVER_CHANNEL: "SERVER_MESSAGE",
  GAME_CHANNEL: "GAME_CHANNEL",
  CLIENT_CHANNEL: "CLIENT_CHANNEL",
  ROOM_CHANNEL: "ROOM_CHANNEL",
  ERROR: "ERROR",
});

export const TYPES = Object.freeze({
  GAME: {
    LEADERBOARD: "LEADERBOARD",
    SEND_DATA: "SEND_DATA",
    START: "START",
    OVER: "OVER",
  },
  CLIENT: {
    SELF_CONNECTED: "SELF_CONNECTED",
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
  },
  ROOM: {
    CREATE_ROOM: "CREATE_ROOM",
    REMOVE_ROOM: "REMOVE_ROOM",
    JOIN_ROOM: "JOIN_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    GET_ALL_ROOMS: "GET_ALL_ROOMS",
    GET_ALL_CLIENTS: "GET_ALL_CLIENTS",
    REMOVE_CLIENT: "REMOVE_CLIENT",
  },
});
export interface clientData {
  topic: string;
  type: string;
}
