export const TOPICS = Object.freeze({
  SERVER_TYPE: "SERVER_TYPE",
  // CLIENT: "CLIENT",
  ROOM_TYPE: "ROOM_TYPE",
});

export const CHANNELS = Object.freeze({
  ERROR_TYPE: "ERROR_TYPE",
  ROOM_TYPE: "ROOM_TYPE",
  CLIENT_TYPE: "CLIENT_TYPE",
  GAME_TYPE: "GAME_TYPE",
});
export const TYPES = Object.freeze({
  GAME: {
    LEADERBOARD: "LEADERBOARD",
    SEND_DATA: "SEND_DATA",
    START: "START",
    OVER: "OVER",
  },
  CLIENT: {
    SELF_CONNECTED: "SELF_CONNECTED",
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    JOIN_PUBLIC_ROOM: "JOIN_PUBLIC_ROOM",
    JOIN_PRIVATE_ROOM: "JOIN_PRIVATE_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
  },
  ROOM: {
    CREATE_ROOM: "CREATE_ROOM",
    REMOVE_ROOM: "REMOVE_ROOM",
    GET_ALL_ROOMS: "GET_ALL_ROOMS",
    GET_ALL_CLIENTS: "GET_ALL_CLIENTS",
    REMOVE_CLIENT: "REMOVE_CLIENT",
    ADD_CLIENT: "ADD_CLIENT",
  },
});
